Controllers and ir.model.access changes
access admin changes and controllers are added with the data rows.

Error: This page isn’t working
localhost redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS