Odoo Server Error
odoo.tools.convert.ParseError: while parsing file:/c:/program%20files/odoo%2016.0.20221201/server/addons/snehith_module/views/snehithmodule_discforum.xml:14
Error while validating view near:

	        <field name="name"/>
	        <field name="description"/>
	       </group>
	 </form>
Field "description" does not exist in model "snehithmodule.discforum"

View error context:
{'file': 'c:\\program files\\odoo '
         '16.0.20221201\\server\\addons\\snehith_module\\views\\snehithmodule_discforum.xml',
 'line': 5,
 'name': 'Disc Data Form',
 'view': ir.ui.view(1314,),
 'view.model': 'snehithmodule.discforum',
 'view.parent': ir.ui.view(),
 'xmlid': 'snehithmodule_discforum_view_form'}

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:8069/web/assets/309-c869f40/web.assets_backend.min.js:957:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8069/web/assets/309-c869f40/web.assets_backend.min.js:964:13)